name: Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7"

      - name: Build
        run: dotnet publish -r linux-musl-x64 --output "./dist" --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Prepare Provisioning
        uses: cschleiden/replace-tokens@v1
        with:
          files: "fly.toml"
        env:
          CLIENT_URL: ${{ secrets.DEV_CLIENT_URL }}

      - name: Deploy
        run: flyctl deploy -a greyboard-hub-dev --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
