name: Deployment

on:
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "7"

      - name: Build
        run: dotnet publish -r linux-musl-x64 --output "./dist" --self-contained true -p:PublishSingleFile=true -p:PublishTrimmed=true

      - uses: superfly/flyctl-actions/setup-flyctl@master

      - name: Copy fly.toml
        run: cp fly.toml fly.toml.bak

      - name: Prepare Provisioning for EU
        uses: cschleiden/replace-tokens@v1
        with:
          files: "fly.toml"
        env:
          REGION: eu
          FLY_REGION: otp
          CLIENT_URLS: ${{ vars.CLIENT_URLS }}

      - name: Deploy to EU
        run: flyctl deploy -a greyboard-hub-eu --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

      - name: Copy fly.toml
        run: cp fly.toml.bak fly.toml

      - name: Prepare Provisioning for US
        uses: cschleiden/replace-tokens@v1
        with:
          files: "fly.toml"
        env:
          REGION: us
          FLY_REGION: dfw
          CLIENT_URLS: ${{ vars.CLIENT_URLS }}

      - name: Deploy to US
        run: flyctl deploy -a greyboard-hub-us --local-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
